/* Generated By:JJTree: Do not edit this line. ASTAnnotation.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTAnnotation extends SimpleNode {
	public ASTAnnotation(int id) {
		super(id);
	}

	public ASTAnnotation(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	public SimpleNode getPred() {
		return (SimpleNode) jjtGetChild(0);
	}

	public SimpleNode getObject() {
		return (SimpleNode) jjtGetChild(1);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {

		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=43b74d3767159350aabe25951f60c097 (do not edit this line) */
