/* Generated By:JJTree: Do not edit this line. ASTHasLangDirFunc.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTHasLangDirFunc extends SimpleNode {
	public ASTHasLangDirFunc(int id) {
		super(id);
	}

	public ASTHasLangDirFunc(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {

		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=7c5f05aac2b128a314f0361e24c075c4 (do not edit this line) */
