/* Generated By:JJTree: Do not edit this line. ASTHasLangFunc.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTHasLangFunc extends SimpleNode {
	public ASTHasLangFunc(int id) {
		super(id);
	}

	public ASTHasLangFunc(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {

		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=c8313328b1fbd20c0484700f78b8e174 (do not edit this line) */
