/* Generated By:JJTree: Do not edit this line. ASTLangDirFunc.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTLangDirFunc extends SimpleNode {
	public ASTLangDirFunc(int id) {
		super(id);
	}

	public ASTLangDirFunc(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {

		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=05374947f3fd0adfce1406b493d2c16b (do not edit this line) */
