/* Generated By:JJTree: Do not edit this line. ASTTripleFunc.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTTripleFunc extends SimpleNode {
	public ASTTripleFunc(int id) {
		super(id);
	}

	public ASTTripleFunc(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	public SimpleNode getSubj() {
		return (SimpleNode) jjtGetChild(0);
	}

	public SimpleNode getPred() {
		return (SimpleNode) jjtGetChild(1);
	}

	public SimpleNode getObj() {
		return (SimpleNode) jjtGetChild(2);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {

		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=bf8bf60b2f3f70dcc1b9c770d4aed49e (do not edit this line) */
