/* Generated By:JJTree: Do not edit this line. ASTVersionDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public class ASTVersionDecl extends SimpleNode {

	private String version;

	public ASTVersionDecl(int id) {
		super(id);
	}

	public ASTVersionDecl(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	/** Accept the visitor. **/
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {

		return visitor.visit(this, data);
	}
}
/* JavaCC - OriginalChecksum=f09e95f86e560818f9fdb5505aa30952 (do not edit this line) */
