/* Generated By:JavaCC: Do not edit this line. SyntaxTreeBuilderTreeConstants.java Version 7.0.12 */
package org.eclipse.rdf4j.query.parser.sparql.ast;

public interface SyntaxTreeBuilderTreeConstants {
	public int JJTUPDATESEQUENCE = 0;
	public int JJTUPDATECONTAINER = 1;
	public int JJTQUERYCONTAINER = 2;
	public int JJTVOID = 3;
	public int JJTBASEDECL = 4;
	public int JJTPREFIXDECL = 5;
	public int JJTVERSIONDECL = 6;
	public int JJTSELECTQUERY = 7;
	public int JJTSELECT = 8;
	public int JJTPROJECTIONELEM = 9;
	public int JJTCONSTRUCTQUERY = 10;
	public int JJTCONSTRUCT = 11;
	public int JJTDESCRIBEQUERY = 12;
	public int JJTDESCRIBE = 13;
	public int JJTASKQUERY = 14;
	public int JJTDATASETCLAUSE = 15;
	public int JJTWHERECLAUSE = 16;
	public int JJTBINDINGSCLAUSE = 17;
	public int JJTINLINEDATA = 18;
	public int JJTBINDINGSET = 19;
	public int JJTBINDINGVALUE = 20;
	public int JJTGROUPCLAUSE = 21;
	public int JJTORDERCLAUSE = 22;
	public int JJTGROUPCONDITION = 23;
	public int JJTHAVINGCLAUSE = 24;
	public int JJTORDERCONDITION = 25;
	public int JJTLIMIT = 26;
	public int JJTOFFSET = 27;
	public int JJTGRAPHPATTERNGROUP = 28;
	public int JJTBASICGRAPHPATTERN = 29;
	public int JJTOPTIONALGRAPHPATTERN = 30;
	public int JJTGRAPHGRAPHPATTERN = 31;
	public int JJTUNIONGRAPHPATTERN = 32;
	public int JJTMINUSGRAPHPATTERN = 33;
	public int JJTSERVICEGRAPHPATTERN = 34;
	public int JJTCONSTRAINT = 35;
	public int JJTFUNCTIONCALL = 36;
	public int JJTTRIPLESSAMESUBJECT = 37;
	public int JJTPROPERTYLIST = 38;
	public int JJTOBJECTLIST = 39;
	public int JJTTRIPLESSAMESUBJECTPATH = 40;
	public int JJTPROPERTYLISTPATH = 41;
	public int JJTPATHALTERNATIVE = 42;
	public int JJTPATHSEQUENCE = 43;
	public int JJTPATHELT = 44;
	public int JJTIRI = 45;
	public int JJTPATHONEINPROPERTYSET = 46;
	public int JJTPATHMOD = 47;
	public int JJTBLANKNODEPROPERTYLIST = 48;
	public int JJTCOLLECTION = 49;
	public int JJTVAR = 50;
	public int JJTREIFIEDTRIPLE = 51;
	public int JJTTRIPLETERM = 52;
	public int JJTCONSTTRIPLETERM = 53;
	public int JJTOR = 54;
	public int JJTAND = 55;
	public int JJTCOMPARE = 56;
	public int JJTINFIX = 57;
	public int JJTMATH = 58;
	public int JJTNOT = 59;
	public int JJTNUMERICLITERAL = 60;
	public int JJTCOUNT = 61;
	public int JJTSUM = 62;
	public int JJTMIN = 63;
	public int JJTMAX = 64;
	public int JJTAVG = 65;
	public int JJTSAMPLE = 66;
	public int JJTGROUPCONCAT = 67;
	public int JJTMD5 = 68;
	public int JJTSHA1 = 69;
	public int JJTSHA224 = 70;
	public int JJTSHA256 = 71;
	public int JJTSHA384 = 72;
	public int JJTSHA512 = 73;
	public int JJTNOW = 74;
	public int JJTYEAR = 75;
	public int JJTMONTH = 76;
	public int JJTDAY = 77;
	public int JJTHOURS = 78;
	public int JJTMINUTES = 79;
	public int JJTSECONDS = 80;
	public int JJTTIMEZONE = 81;
	public int JJTTZ = 82;
	public int JJTRAND = 83;
	public int JJTABS = 84;
	public int JJTCEIL = 85;
	public int JJTFLOOR = 86;
	public int JJTROUND = 87;
	public int JJTSUBSTR = 88;
	public int JJTSTRLEN = 89;
	public int JJTUPPERCASE = 90;
	public int JJTLOWERCASE = 91;
	public int JJTSTRSTARTS = 92;
	public int JJTSTRENDS = 93;
	public int JJTSTRBEFORE = 94;
	public int JJTSTRAFTER = 95;
	public int JJTREPLACE = 96;
	public int JJTCONCAT = 97;
	public int JJTCONTAINS = 98;
	public int JJTENCODEFORURI = 99;
	public int JJTIF = 100;
	public int JJTIN = 101;
	public int JJTNOTIN = 102;
	public int JJTCOALESCE = 103;
	public int JJTSTR = 104;
	public int JJTLANG = 105;
	public int JJTLANGMATCHES = 106;
	public int JJTDATATYPE = 107;
	public int JJTBOUND = 108;
	public int JJTSAMETERM = 109;
	public int JJTISIRI = 110;
	public int JJTISBLANK = 111;
	public int JJTISLITERAL = 112;
	public int JJTISNUMERIC = 113;
	public int JJTBNODEFUNC = 114;
	public int JJTIRIFUNC = 115;
	public int JJTSTRDT = 116;
	public int JJTSTRLANG = 117;
	public int JJTUUID = 118;
	public int JJTSTRUUID = 119;
	public int JJTBIND = 120;
	public int JJTREGEXEXPRESSION = 121;
	public int JJTEXISTSFUNC = 122;
	public int JJTNOTEXISTSFUNC = 123;
	public int JJTISTRIPLE = 124;
	public int JJTTRIPLEFUNC = 125;
	public int JJTSUBJECTFUNC = 126;
	public int JJTPREDICATEFUNC = 127;
	public int JJTOBJECTFUNC = 128;
	public int JJTLANGDIRFUNC = 129;
	public int JJTHASLANGFUNC = 130;
	public int JJTHASLANGDIRFUNC = 131;
	public int JJTSTRLANGDIRFUNC = 132;
	public int JJTRDFLITERAL = 133;
	public int JJTTRUE = 134;
	public int JJTFALSE = 135;
	public int JJTSTRING = 136;
	public int JJTQNAME = 137;
	public int JJTBLANKNODE = 138;
	public int JJTGRAPHREFALL = 139;
	public int JJTGRAPHORDEFAULT = 140;
	public int JJTUNPARSEDQUADDATABLOCK = 141;
	public int JJTQUADSNOTTRIPLES = 142;
	public int JJTLOAD = 143;
	public int JJTCLEAR = 144;
	public int JJTDROP = 145;
	public int JJTADD = 146;
	public int JJTMOVE = 147;
	public int JJTCOPY = 148;
	public int JJTCREATE = 149;
	public int JJTINSERTDATA = 150;
	public int JJTDELETEDATA = 151;
	public int JJTDELETEWHERE = 152;
	public int JJTDELETECLAUSE = 153;
	public int JJTINSERTCLAUSE = 154;
	public int JJTMODIFY = 155;

	public String[] jjtNodeName = {
			"UpdateSequence",
			"UpdateContainer",
			"QueryContainer",
			"void",
			"BaseDecl",
			"PrefixDecl",
			"VersionDecl",
			"SelectQuery",
			"Select",
			"ProjectionElem",
			"ConstructQuery",
			"Construct",
			"DescribeQuery",
			"Describe",
			"AskQuery",
			"DatasetClause",
			"WhereClause",
			"BindingsClause",
			"InlineData",
			"BindingSet",
			"BindingValue",
			"GroupClause",
			"OrderClause",
			"GroupCondition",
			"HavingClause",
			"OrderCondition",
			"Limit",
			"Offset",
			"GraphPatternGroup",
			"BasicGraphPattern",
			"OptionalGraphPattern",
			"GraphGraphPattern",
			"UnionGraphPattern",
			"MinusGraphPattern",
			"ServiceGraphPattern",
			"Constraint",
			"FunctionCall",
			"TriplesSameSubject",
			"PropertyList",
			"ObjectList",
			"TriplesSameSubjectPath",
			"PropertyListPath",
			"PathAlternative",
			"PathSequence",
			"PathElt",
			"IRI",
			"PathOneInPropertySet",
			"PathMod",
			"BlankNodePropertyList",
			"Collection",
			"Var",
			"ReifiedTriple",
			"TripleTerm",
			"ConstTripleTerm",
			"Or",
			"And",
			"Compare",
			"Infix",
			"Math",
			"Not",
			"NumericLiteral",
			"Count",
			"Sum",
			"Min",
			"Max",
			"Avg",
			"Sample",
			"GroupConcat",
			"MD5",
			"SHA1",
			"SHA224",
			"SHA256",
			"SHA384",
			"SHA512",
			"Now",
			"Year",
			"Month",
			"Day",
			"Hours",
			"Minutes",
			"Seconds",
			"Timezone",
			"Tz",
			"Rand",
			"Abs",
			"Ceil",
			"Floor",
			"Round",
			"Substr",
			"StrLen",
			"UpperCase",
			"LowerCase",
			"StrStarts",
			"StrEnds",
			"StrBefore",
			"StrAfter",
			"Replace",
			"Concat",
			"Contains",
			"EncodeForURI",
			"If",
			"In",
			"NotIn",
			"Coalesce",
			"Str",
			"Lang",
			"LangMatches",
			"Datatype",
			"Bound",
			"SameTerm",
			"IsIRI",
			"IsBlank",
			"IsLiteral",
			"IsNumeric",
			"BNodeFunc",
			"IRIFunc",
			"StrDt",
			"StrLang",
			"UUID",
			"STRUUID",
			"Bind",
			"RegexExpression",
			"ExistsFunc",
			"NotExistsFunc",
			"IsTriple",
			"TripleFunc",
			"SubjectFunc",
			"PredicateFunc",
			"ObjectFunc",
			"LangDirFunc",
			"HasLangFunc",
			"HasLangDirFunc",
			"StrLangDirFunc",
			"RDFLiteral",
			"True",
			"False",
			"String",
			"QName",
			"BlankNode",
			"GraphRefAll",
			"GraphOrDefault",
			"UnparsedQuadDataBlock",
			"QuadsNotTriples",
			"Load",
			"Clear",
			"Drop",
			"Add",
			"Move",
			"Copy",
			"Create",
			"InsertData",
			"DeleteData",
			"DeleteWhere",
			"DeleteClause",
			"InsertClause",
			"Modify",
	};
}
/* JavaCC - OriginalChecksum=1f283b62d3468ce387ca998cd72e67ff (do not edit this line) */
